export const CSS = [
  '@font-face { font-family:"HabitSmall"; src:url("https://app.lofi.town/fonts/habit_small.ttf") format("truetype"); }',
  "#lt-hud { position:fixed;left:10px;top:50%;transform:translateY(-50%);z-index:999999;",
  '  background:var(--lt-bg, #1e1e3a);color:var(--lt-text, #c8c0e0);font-family:"HabitSmall",monospace;',
  "  width:280px;user-select:none;overflow:hidden;",
  "  border:3px solid var(--lt-border, #3a3a6a);border-radius:12px;",
  "  box-shadow:0 4px 20px var(--lt-shadow, rgba(0,0,0,0.5));",
  "  image-rendering:pixelated; }",
  "#lt-hud .lt-header { padding:12px 14px;background:var(--lt-bg-secondary, #2a2a50);",
  "  border-bottom:2px solid var(--lt-border, #3a3a6a);display:flex;align-items:center;cursor:grab;",
  "  border-radius:9px 9px 0 0; }",
  "#lt-hud .lt-title-group { display:flex;flex-direction:column;flex:1;min-width:0; }",
  "#lt-hud .lt-header span.lt-title { font-size:22px;color:var(--lt-text-title, #b8b0d8);letter-spacing:0.5px; }",
  "#lt-hud .lt-header span.lt-ver { font-size:12px;color:var(--lt-text-muted, #6a6a9a);margin-top:-1px; }",
  "#lt-toast-container { position:fixed;top:55px;right:55px;z-index:999999;display:flex;flex-direction:column;gap:6px;max-width:280px;pointer-events:none; }",
  '.lt-toast { background:var(--lt-bg-secondary, rgba(30,30,58,0.92));border:1px solid var(--lt-border, rgba(58,58,106,0.6));border-left:3px solid var(--lt-accent, #8a8abe);border-radius:6px;padding:8px 12px;font-family:"HabitSmall",monospace;font-size:14px;color:var(--lt-text, #c8c0e0);pointer-events:auto;backdrop-filter:blur(8px);animation:lt-toast-in 0.25s ease;word-wrap:break-word;opacity:0.95; }',
  ".lt-toast-success { border-left-color:#5ad85a;color:#5ad85a; }",
  ".lt-toast-error { border-left-color:#f05050;color:#f05050; }",
  "@keyframes lt-toast-in { from { opacity:0;transform:translateX(20px); } to { opacity:1;transform:translateX(0); } }",
  ".lt-toast-exit { animation:lt-toast-out 0.3s ease forwards; }",
  "@keyframes lt-toast-out { from { opacity:1;transform:translateX(0); } to { opacity:0;transform:translateX(20px); } }",
  "#lt-hud .lt-header button.lt-back-btn { border:none;background:none;color:var(--lt-accent, #8a8abe);",
  "  cursor:pointer;font-size:32px;padding:0 14px 2px 0;font-family:inherit;line-height:1;vertical-align:middle; }",
  "#lt-hud .lt-header button.lt-back-btn:hover { color:var(--lt-text, #c8c0e0); }",
  "#lt-hud .lt-status-bar { display:flex;flex-wrap:wrap;gap:3px;flex:1;min-width:0;align-items:center;justify-content:flex-end; }",
  "#lt-hud .lt-status-bar:empty { display:none; }",
  "#lt-hud .lt-badge { font-size:10px;font-weight:700;letter-spacing:0.5px;padding:1px 6px;border-radius:3px;white-space:nowrap;line-height:1.4; }",
  "#lt-hud .lt-body { padding:6px 0; }",
  "#lt-hud .lt-item { display:flex;align-items:center;justify-content:space-between;",
  "  padding:10px 14px;cursor:pointer;border:none;background:none;color:var(--lt-text, #c8c0e0);",
  "  width:100%;font-size:18px;font-family:inherit;text-align:left; }",
  "#lt-hud .lt-item:hover { background:var(--lt-bg-secondary, #2a2a50); }",
  "#lt-hud .lt-item .lt-arrow { color:var(--lt-text-muted, #6a6a9a);font-size:16px; }",
  "#lt-hud .lt-item .lt-tag { font-size:13px;color:var(--lt-accent, #8a8abe);margin-left:8px;",
  "  background:var(--lt-bg-secondary, #2a2a50);padding:2px 6px;border:1px solid var(--lt-border-light, #4a4a7a);border-radius:4px; }",
  "#lt-hud .lt-item .lt-sub { font-size:14px;color:var(--lt-text-muted, #6a6a9a); }",
  "#lt-hud .lt-sep { border-top:2px solid var(--lt-bg-secondary, #2a2a50);margin:4px 12px; }",
  "#lt-hud .lt-action { display:block;width:calc(100% - 24px);margin:5px 12px;padding:10px 0;",
  "  border:2px solid var(--lt-border-light, #4a4a7a);cursor:pointer;font-size:17px;color:var(--lt-text, #c8c0e0);",
  "  text-align:center;font-family:inherit;background:var(--lt-bg-secondary, #2a2a50);border-radius:6px; }",
  "#lt-hud .lt-action:hover { background:var(--lt-border, #3a3a6a);color:var(--lt-text, #e0d8f0); }",
  "#lt-hud .lt-action.lt-primary { background:var(--lt-bg-secondary, #2a2a50); }",
  "#lt-hud .lt-action.lt-success { background:#1a3a1a;border-color:#2a6a2a;color:#6abe6a; }",
  "#lt-hud .lt-action.lt-success:hover { background:#2a4a2a; }",
  "#lt-hud .lt-action.lt-danger { background:#3a1a1a;border-color:#6a2a2a;color:#be6a6a; }",
  "#lt-hud .lt-action.lt-danger:hover { background:#4a2a2a; }",
  "#lt-hud .lt-action.lt-muted { background:var(--lt-bg, #1e1e3a);border-color:var(--lt-border, #3a3a6a);color:var(--lt-text-muted, #6a6a9a); }",
  "#lt-modal-overlay .lt-action { display:block;width:100%;padding:10px 0;border:2px solid var(--lt-border-light, #4a4a7a);cursor:pointer;font-size:17px;color:var(--lt-text, #c8c0e0);text-align:center;font-family:inherit;background:var(--lt-bg-secondary, #2a2a50);border-radius:6px;box-sizing:border-box; }",
  "#lt-modal-overlay .lt-action:hover { background:var(--lt-border, #3a3a6a);color:var(--lt-text, #e0d8f0); }",
  "#lt-modal-overlay .lt-action.lt-success { background:#1a3a1a;border-color:#2a6a2a;color:#6abe6a; }",
  "#lt-modal-overlay .lt-action.lt-success:hover { background:#2a4a2a; }",
  "#lt-modal-overlay .lt-action.lt-muted { background:var(--lt-bg, #1e1e3a);border-color:var(--lt-border, #3a3a6a);color:var(--lt-text-muted, #6a6a9a); }",
  "#lt-hud .lt-status { font-size:15px;color:var(--lt-text-muted, #6a6a9a);text-align:center;padding:6px 14px;min-height:18px; }",
  "#lt-hud .lt-input { background:var(--lt-input-bg, #14142a);border:2px solid var(--lt-border, #3a3a6a);border-radius:6px;",
  "  color:var(--lt-text, #c8c0e0);font-size:16px;padding:8px 10px;width:calc(100% - 24px);margin:5px 12px;",
  "  box-sizing:border-box;outline:none;font-family:inherit; }",
  "#lt-hud .lt-input:focus { border-color:var(--lt-accent, #6a6abe);background:var(--lt-input-bg, #1a1a30); }",
  "#lt-hud .lt-stat-row { display:flex;justify-content:space-between;padding:4px 14px;font-size:17px; }",
  "#lt-hud .lt-warn { font-size:13px;color:var(--lt-text-muted, #5a5a8a);text-align:center;padding:6px 14px; }",
  "#lt-hud .lt-wp-row { display:flex;align-items:center;gap:0; }",
  "#lt-hud .lt-wp-row .lt-item { flex:1; }",
  "#lt-hud .lt-wp-row .lt-del { border:none;background:none;color:#be6a6a;",
  "  cursor:pointer;padding:10px 12px;font-size:17px;font-family:inherit; }",
  "#lt-hud .lt-wp-row .lt-del:hover { color:#e07070;background:#3a1a1a; }",
  "#lt-modal-overlay { position:fixed;inset:0;z-index:9999999;background:rgba(0,0,0,0.6);",
  "  display:flex;align-items:center;justify-content:center; }",
  "#lt-modal { background:var(--lt-bg, #1e1e3a);border:3px solid var(--lt-border, #3a3a6a);border-radius:12px;padding:20px 22px;",
  '  width:320px;font-family:"HabitSmall",monospace;color:var(--lt-text, #c8c0e0);box-shadow:0 4px 20px rgba(0,0,0,0.6); }',
  "#lt-modal-title { font-size:28px;font-weight:700;margin-bottom:10px; }",
  "#lt-modal-msg { font-size:21px;color:var(--lt-text-muted, #8a8aaa);margin-bottom:18px;line-height:1.4; }",
  "#lt-modal-actions { display:flex;gap:10px; }",
  "#lt-modal-actions button { flex:1;padding:9px 0;border-radius:6px;border:2px solid;",
  '  cursor:pointer;font-size:22px;font-family:"HabitSmall",monospace; }',
  "#lt-modal-actions button:hover { filter:brightness(1.2); }",
  "#lt-hud .lt-item.lt-kb-focus, #lt-hud .lt-action.lt-kb-focus { background:var(--lt-border, #3a3a6a);outline:2px solid var(--lt-accent, #6a6abe);outline-offset:-2px; }",
  "#lt-hud .lt-dev-label { font-size:12px;color:#6a6a9a;text-align:center;padding:4px 14px 0;letter-spacing:2px;opacity:0.6; }",
  "#lt-hud .lt-dev-row { display:flex;gap:6px;padding:0 12px;margin:5px 0; }",
  "#lt-hud .lt-dev-row .lt-action { flex:1;margin:0; }",
  "#lt-hud .lt-empty { font-size:15px;color:var(--lt-text-muted, #6a6a9a);text-align:center;padding:14px; }",
  "#lt-hud .lt-player-info { font-size:15px;padding:8px 14px;text-align:center; }",
  "#lt-players-modal { position:fixed;inset:0;z-index:9999999;background:rgba(0,0,0,0.65);",
  "  display:flex;align-items:center;justify-content:center; }",
  "#lt-players-modal .lt-pm-box { background:var(--lt-bg, #1e1e3a);border:3px solid var(--lt-border, #3a3a6a);",
  '  border-radius:12px;width:600px;max-width:90vw;max-height:80vh;display:flex;flex-direction:column;font-family:"HabitSmall",monospace;',
  "  color:var(--lt-text, #c8c0e0);box-shadow:0 4px 24px rgba(0,0,0,0.6);overflow:hidden; }",
  "#lt-players-modal .lt-pm-header { padding:12px 16px;background:var(--lt-bg-secondary, #2a2a50);",
  "  border-bottom:2px solid var(--lt-border, #3a3a6a);display:flex;align-items:center;gap:12px; }",
  "#lt-players-modal .lt-pm-header .lt-pm-title { font-size:22px;flex:1;color:var(--lt-text-title, #b8b0d8); }",
  "#lt-players-modal .lt-pm-header .lt-pm-close { border:none;background:none;color:var(--lt-text-muted, #6a6a9a);",
  "  cursor:pointer;font-size:24px;font-family:inherit;padding:0 4px; }",
  "#lt-players-modal .lt-pm-header .lt-pm-close:hover { color:var(--lt-text, #c8c0e0); }",
  "#lt-players-modal .lt-pm-search { margin:10px 12px 6px;background:var(--lt-input-bg, #14142a);",
  "  border:2px solid var(--lt-border, #3a3a6a);border-radius:6px;color:var(--lt-text, #c8c0e0);",
  "  font-size:16px;padding:8px 10px;outline:none;font-family:inherit;box-sizing:border-box;width:calc(100% - 24px); }",
  "#lt-players-modal .lt-pm-search:focus { border-color:var(--lt-accent, #6a6abe); }",
  "#lt-players-modal .lt-pm-grid { display:grid;grid-template-columns:repeat(auto-fill, minmax(180px, 1fr));",
  "  gap:6px;padding:10px 12px;overflow-y:auto;flex:1;min-height:0;align-content:start; }",
  "#lt-players-modal .lt-pm-cell { padding:10px 8px;border:2px solid var(--lt-border-light, #4a4a7a);",
  "  border-radius:6px;cursor:pointer;background:var(--lt-bg-secondary, #2a2a50);text-align:center;",
  "  font-size:17px;font-family:inherit;color:var(--lt-text, #c8c0e0);line-height:1.3;word-break:break-word; }",
  "#lt-players-modal .lt-pm-cell:hover:not([disabled]) { background:var(--lt-border, #3a3a6a);color:var(--lt-text, #e0d8f0); }",
  "#lt-players-modal .lt-pm-cell[disabled] { cursor:default;opacity:0.6; }",
  "#lt-players-modal .lt-pm-cell.lt-pm-away { border-color:var(--lt-border, #3a3a6a); }",
  "#lt-players-modal .lt-pm-cell.lt-pm-offline { border-color:var(--lt-bg-secondary, #2a2a50);opacity:0.4; }",
  "#lt-players-modal .lt-pm-sub { font-size:13px;color:var(--lt-text-muted, #6a6a9a);margin-top:2px; }",
  "#lt-hud .lt-name-stack { display:flex;flex-direction:column;gap:1px;line-height:1.2; }",
  "#lt-hud .lt-username { font-size:13px;color:var(--lt-text-muted, #6a6a9a); }",
  "#lt-hud .lt-friend-away { cursor:default;opacity:0.6; }",
  "#lt-hud .lt-friend-away .lt-sub { font-style:italic; }",
  "#lt-hud .lt-info-note { font-size:13px;color:var(--lt-accent, #8a8abe);text-align:center;padding:6px 14px;cursor:pointer; }",
  "#lt-hud .lt-info-note:hover { color:var(--lt-text, #c8c0e0); }",
  "#lt-players-modal .lt-info-note { grid-column:1/-1;font-size:13px;color:var(--lt-accent, #8a8abe);text-align:center;padding:8px;cursor:pointer; }",
  "#lt-players-modal .lt-info-note:hover { color:var(--lt-text, #c8c0e0); }",
  "#lt-hud .lt-tabs { display:flex;gap:0;margin:0 12px 4px;border:2px solid var(--lt-border, #3a3a6a);border-radius:6px;overflow:hidden; }",
  "#lt-hud .lt-tab { flex:1;padding:7px 0;border:none;cursor:pointer;font-size:15px;font-family:inherit;",
  "  text-align:center;background:var(--lt-bg, #1e1e3a);color:var(--lt-text-muted, #6a6a9a); }",
  "#lt-hud .lt-tab:not(:last-child) { border-right:2px solid var(--lt-border, #3a3a6a); }",
  "#lt-hud .lt-tab:hover { background:var(--lt-bg-secondary, #2a2a50); }",
  "#lt-hud .lt-tab.lt-tab-active { background:var(--lt-bg-secondary, #2a2a50);color:var(--lt-text, #c8c0e0); }",
  "#lt-players-modal .lt-tabs { display:flex;gap:0;margin:6px 12px 0;border:2px solid var(--lt-border, #3a3a6a);border-radius:6px;overflow:hidden; }",
  "#lt-players-modal .lt-tab { flex:1;padding:7px 0;border:none;cursor:pointer;font-size:15px;font-family:inherit;",
  "  text-align:center;background:var(--lt-bg, #1e1e3a);color:var(--lt-text-muted, #6a6a9a); }",
  "#lt-players-modal .lt-tab:not(:last-child) { border-right:2px solid var(--lt-border, #3a3a6a); }",
  "#lt-players-modal .lt-tab:hover { background:var(--lt-bg-secondary, #2a2a50); }",
  "#lt-players-modal .lt-tab.lt-tab-active { background:var(--lt-bg-secondary, #2a2a50);color:var(--lt-text, #c8c0e0); }",
  "#lt-hud .lt-speed-row { display:flex;align-items:center;gap:10px;padding:8px 14px; }",
  "#lt-hud .lt-speed-label { font-size:15px;color:var(--lt-text-muted, #6a6a9a);white-space:nowrap; }",
  "#lt-hud .lt-slider { flex:1;-webkit-appearance:none;appearance:none;height:6px;border-radius:3px;",
  "  background:var(--lt-border, #3a3a6a);outline:none;cursor:pointer; }",
  "#lt-hud .lt-slider::-webkit-slider-thumb { -webkit-appearance:none;appearance:none;width:16px;height:16px;",
  "  border-radius:50%;background:var(--lt-accent, #8a8abe);border:2px solid var(--lt-border-light, #4a4a7a);cursor:pointer; }",
  "#lt-hud .lt-action-select { display:flex;align-items:center;justify-content:center;gap:8px;padding:10px 12px; }",
  "#lt-hud .lt-action-sel { background:none;border:1px solid var(--lt-border-light, #4a4a7a);",
  "  border-radius:4px;color:var(--lt-text-muted, #6a6a9a);font-size:14px;font-family:inherit;padding:2px 6px;cursor:pointer; }",
  "#lt-hud .lt-action-sel:focus { border-color:var(--lt-accent, #6a6abe); }",
  "#lt-hud .lt-action-select:hover .lt-action-sel { border-color:var(--lt-border, #5a5a8a); }",
  "#lt-transition { position:fixed;inset:0;z-index:999998;background:#000;opacity:0;pointer-events:none;transition:opacity 0.4s ease; }",
  "#lt-transition.lt-fade-in { opacity:1;pointer-events:all; }",
  "#lt-sounds-modal { position:fixed;inset:0;z-index:9999999;background:rgba(0,0,0,0.65);display:flex;align-items:center;justify-content:center; }",
  '#lt-sounds-modal .lt-sm-box { background:var(--lt-bg,#1e1e3a);border:3px solid var(--lt-border,#3a3a6a);border-radius:12px;width:680px;max-width:90vw;max-height:85vh;display:flex;flex-direction:column;font-family:"HabitSmall",monospace;color:var(--lt-text,#c8c0e0);box-shadow:0 4px 24px rgba(0,0,0,0.6);overflow:hidden; }',
  "#lt-sounds-modal .lt-sm-header { padding:12px 16px;background:var(--lt-bg-secondary,#2a2a50);border-bottom:2px solid var(--lt-border,#3a3a6a);display:flex;align-items:center;gap:12px; }",
  "#lt-sounds-modal .lt-sm-title { font-size:22px;flex:1;color:var(--lt-text-title,#b8b0d8); }",
  "#lt-sounds-modal .lt-sm-close { border:none;background:none;color:var(--lt-text-muted,#6a6a9a);cursor:pointer;font-size:24px;font-family:inherit;padding:0 4px; }",
  "#lt-sounds-modal .lt-sm-close:hover { color:var(--lt-text,#c8c0e0); }",
  "#lt-sounds-modal .lt-sm-body { padding:12px 16px;overflow-y:auto;flex:1;min-height:0; }",
  "#lt-sounds-modal .lt-sm-warn { font-size:13px;color:var(--lt-text-muted,#5a5a8a);text-align:center;padding:6px 0 10px; }",
  // ── Music card (now-playing + controls unified) ──
  "#lt-sounds-modal .lt-sm-music-card { border:1px solid var(--lt-border-light,#4a4a7a);border-radius:6px;background:var(--lt-bg-secondary,#2a2a50);margin-bottom:12px;overflow:hidden; }",
  "#lt-sounds-modal .lt-sm-np { display:flex;align-items:center;gap:12px;padding:10px 12px; }",
  "#lt-sounds-modal .lt-sm-np-art { width:48px;height:48px;border-radius:6px;object-fit:cover;flex-shrink:0;background:var(--lt-bg,#1e1e3a); }",
  "#lt-sounds-modal .lt-sm-np-info { flex:1;min-width:0; }",
  "#lt-sounds-modal .lt-sm-np-title { font-size:16px;color:var(--lt-text,#c8c0e0);white-space:nowrap;overflow:hidden;text-overflow:ellipsis; }",
  "#lt-sounds-modal .lt-sm-np-artist { display:flex;align-items:center;gap:8px;font-size:13px;color:var(--lt-text-muted,#6a6a9a); }",
  "#lt-sounds-modal .lt-sm-np-time { font-size:13px;color:var(--lt-text-muted,#6a6a9a);white-space:nowrap;flex-shrink:0; }",
  "#lt-sounds-modal .lt-sm-np-progress { height:3px;background:var(--lt-border,#3a3a6a);overflow:hidden; }",
  "#lt-sounds-modal .lt-sm-np-bar { height:100%;background:var(--lt-accent,#8a8abe);transition:width 1s linear; }",
  "#lt-sounds-modal .lt-sm-resync-inline { font-size:11px;padding:2px 8px;border:1px solid var(--lt-border-light,#4a4a7a);border-radius:4px;background:var(--lt-bg,#1e1e3a);color:var(--lt-text-muted,#6a6a9a);cursor:pointer;white-space:nowrap;flex-shrink:0;font-family:inherit; }",
  "#lt-sounds-modal .lt-sm-resync-inline:hover:not(:disabled) { background:var(--lt-border,#3a3a6a);color:var(--lt-text,#c8c0e0); }",
  "#lt-sounds-modal .lt-sm-resync-inline:disabled { opacity:0.3;cursor:default; }",
  "#lt-sounds-modal .lt-sm-controls { display:flex;align-items:center;padding:8px 12px;gap:10px; }",
  "#lt-sounds-modal .lt-sm-music-label { font-size:14px;color:var(--lt-text-muted,#6a6a9a);flex-shrink:0; }",
  "#lt-sounds-modal .lt-sm-slider { flex:1;-webkit-appearance:none;appearance:none;height:6px;border-radius:3px;background:var(--lt-border,#3a3a6a);outline:none;cursor:pointer; }",
  "#lt-sounds-modal .lt-sm-slider::-webkit-slider-thumb { -webkit-appearance:none;appearance:none;width:14px;height:14px;border-radius:50%;background:var(--lt-accent,#8a8abe);border:2px solid var(--lt-border-light,#4a4a7a);cursor:pointer; }",
  "#lt-sounds-modal .lt-sm-vol-val { font-size:13px;color:var(--lt-text-muted,#6a6a9a);min-width:24px;text-align:right;flex-shrink:0; }",
  // ── Shared button base ──
  "#lt-sounds-modal .lt-sm-btn { border:1px solid var(--lt-border-light,#4a4a7a);border-radius:6px;padding:8px 6px;font-size:14px;font-family:inherit;color:var(--lt-text,#c8c0e0);background:var(--lt-bg-secondary,#2a2a50);cursor:pointer;text-align:center;white-space:nowrap;overflow:hidden;text-overflow:ellipsis; }",
  "#lt-sounds-modal .lt-sm-btn:hover:not(.lt-sm-off) { background:var(--lt-border,#3a3a6a); }",
  "#lt-sounds-modal .lt-sm-btn.lt-sm-off { opacity:0.4;color:var(--lt-text-muted,#6a6a9a);background:var(--lt-bg,#1e1e3a); }",
  "#lt-sounds-modal .lt-sm-btn.lt-sm-on { background:var(--lt-border,#3a3a6a); }",
  // ── Icon button ──
  "#lt-sounds-modal .lt-sm-icon { display:inline-flex;align-items:center;justify-content:center;width:36px;height:36px;padding:0;flex-shrink:0; }",
  "#lt-sounds-modal .lt-sm-icon svg { display:block; }",
  // ── Toggles row ──
  "#lt-sounds-modal .lt-sm-toggles { display:flex;gap:6px;margin-bottom:14px;align-items:center; }",
  "#lt-sounds-modal .lt-sm-toggles .lt-sm-btn { flex:1; }",
  "#lt-sounds-modal .lt-sm-toggles .lt-sm-icon { flex:0 0 36px; }",
  "#lt-sounds-modal .lt-sm-toggles .lt-sm-test { flex:0 0 auto;padding:8px 14px;display:inline-flex;align-items:center;gap:5px; }",
  "#lt-sounds-modal .lt-sm-toggles .lt-sm-test svg { display:block;flex-shrink:0; }",
  // ── Separator ──
  "#lt-sounds-modal .lt-sm-sep { border-top:1px solid var(--lt-border-light,#4a4a7a);margin:14px 0; }",
  // ── Sound grid ──
  "#lt-sounds-modal .lt-sm-sections { display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:4px 20px; }",
  "#lt-sounds-modal .lt-sm-cat { padding:8px 0 4px;font-size:13px;color:var(--lt-text-muted,#6a6a9a);letter-spacing:1px; }",
  "#lt-sounds-modal .lt-sm-grid { display:grid;grid-template-columns:repeat(3,1fr);gap:6px;padding:4px 0 8px; }",
  "#lt-sounds-modal .lt-sm-cell { border:1px solid var(--lt-border-light,#4a4a7a);border-radius:6px;padding:8px 6px;font-size:14px;font-family:inherit;color:var(--lt-text,#c8c0e0);background:var(--lt-bg-secondary,#2a2a50);cursor:pointer;text-align:center;white-space:nowrap;overflow:hidden;text-overflow:ellipsis; }",
  "#lt-sounds-modal .lt-sm-cell:hover:not(.lt-sm-muted) { background:var(--lt-border,#3a3a6a); }",
  "#lt-sounds-modal .lt-sm-cell.lt-sm-muted { opacity:0.4;text-decoration:line-through;color:var(--lt-text-muted,#6a6a9a);background:var(--lt-bg,#1e1e3a); }",
].join(" ");
